version: '3.9'

services:
  

  postgres-compose:
    image: phdcoder/postgresbr
    restart: always
    container_name: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data/pgdata
      - ./initdb:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_PASSWORD: "${DB_PW}"
      PGDATA: /var/lib/postgresql/data/pgdata
      LANG: pt_BR.utf8
    ports:
      - "5455:5432"
    networks:
      network:
        aliases:
            - postgresdb
  
    
  pgadmin-compose:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "${PG_EMAIL}"
      PGADMIN_DEFAULT_PASSWORD: "${PG_PW}"
    ports:
      - 15432:80
    depends_on:
      - postgres-compose
    networks:
      - network
  

networks:
  network:
    driver: bridge

volumes:
  postgres-data:
  